#### Data formatting

Erasing previous year registers and visualizing the data just in case

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

adj_close = pd.read_csv('C:\\Users\\jtjua\\arturo\\Wasserstein-Kelly\\data\\processed\\monthly_adj_close.csv', index_col=0, parse_dates=True)
adj_close.head()

,AAPL,MSFT,AMZN,JPM,JNJ,XOM,PG,CAT,KO,WMT
Date,,,,,,,,,,
2010-01-31,5.744444,20.966568,6.2705,25.583509,38.849991,34.826008,38.116680,35.080994,16.363693,12.718754
2010-02-28,6.120109,21.430885,5.9200,27.574217,39.234425,35.363308,39.188019,38.311069,15.902185,12.871099
2010-03-31,7.028761,21.894333,6.7885,29.400681,40.604519,36.440540,39.181839,42.205971,16.725695,13.309911
2010-04-30,7.809104,22.828714,6.8550,28.006285,40.044029,36.870319,38.790703,46.010025,16.254328,12.840713
2010-05-31,7.683186,19.372578,6.2730,26.033087,36.639038,33.116699,38.122978,41.056988,15.630924,12.173717

In [3]:
#Dropping registers fromm 2009-12-31
adj_close.drop(adj_close[adj_close.index < '2010-01-01'].index, inplace=True)
adj_close.head()

,AAPL,MSFT,AMZN,JPM,JNJ,XOM,PG,CAT,KO,WMT
Date,,,,,,,,,,
2010-01-31,5.744444,20.966568,6.2705,25.583509,38.849991,34.826008,38.116680,35.080994,16.363693,12.718754
2010-02-28,6.120109,21.430885,5.9200,27.574217,39.234425,35.363308,39.188019,38.311069,15.902185,12.871099
2010-03-31,7.028761,21.894333,6.7885,29.400681,40.604519,36.440540,39.181839,42.205971,16.725695,13.309911
2010-04-30,7.809104,22.828714,6.8550,28.006285,40.044029,36.870319,38.790703,46.010025,16.254328,12.840713
2010-05-31,7.683186,19.372578,6.2730,26.033087,36.639038,33.116699,38.122978,41.056988,15.630924,12.173717

In [4]:
 monthly_panel = pd.read_csv('C:\\Users\\jtjua\\arturo\\Wasserstein-Kelly\\data\\processed\\monthly_panel.csv', index_col=0, parse_dates=True)
monthly_panel.drop(monthly_panel[monthly_panel.index < '2010-01-01'].index, inplace=True)
monthly_panel.head()

,AAPL,MSFT,AMZN,JPM,JNJ,XOM,PG,CAT,KO,WMT,mkt_return,vix,rf_return
Date,,,,,,,,,,,,,
2010-01-31,-0.088597,-0.075459,-0.067722,-0.064392,-0.024064,-0.055140,0.022463,-0.077094,-0.048245,-0.000374,-0.036342,24.620001,0.000067
2010-02-28,0.065396,0.022146,-0.055897,0.077812,0.009895,0.015428,0.028107,0.092075,-0.028203,0.011978,0.031195,19.500000,0.000108
2010-03-31,0.148470,0.021625,0.146706,0.066238,0.034921,0.030462,-0.000158,0.101665,0.051786,0.034093,0.060880,17.590000,0.000133
2010-04-30,0.111021,0.042677,0.009796,-0.047427,-0.013804,0.011794,-0.009983,0.090131,-0.028182,-0.035252,0.015470,22.049999,0.000133
2010-05-31,-0.016125,-0.151394,-0.084902,-0.070456,-0.085031,-0.101806,-0.017214,-0.107651,-0.038353,-0.051944,-0.079455,32.070000,0.000133

Already converted into monthly returns, thank god

In [ ]:
monthly_panel

,AAPL,MSFT,AMZN,JPM,JNJ,XOM,PG,CAT,KO,WMT,mkt_return,vix,rf_return
Date,,,,,,,,,,,,,
2010-01-31,-0.088597,-0.075459,-0.067722,-0.064392,-0.024064,-0.055140,0.022463,-0.077094,-0.048245,-0.000374,-0.036342,24.620001,0.000067
2010-02-28,0.065396,0.022146,-0.055897,0.077812,0.009895,0.015428,0.028107,0.092075,-0.028203,0.011978,0.031195,19.500000,0.000108
2010-03-31,0.148470,0.021625,0.146706,0.066238,0.034921,0.030462,-0.000158,0.101665,0.051786,0.034093,0.060880,17.590000,0.000133
2010-04-30,0.111021,0.042677,0.009796,-0.047427,-0.013804,0.011794,-0.009983,0.090131,-0.028182,-0.035252,0.015470,22.049999,0.000133
2010-05-31,-0.016125,-0.151394,-0.084902,-0.070456,-0.085031,-0.101806,-0.017214,-0.107651,-0.038353,-0.051944,-0.079455,32.070000,0.000133
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-08-31,0.119639,-0.048692,-0.021827,0.017486,0.083346,0.033263,0.043663,-0.043331,0.016203,-0.007894,0.020519,15.360000,0.003458
2025-09-30,0.096881,0.022223,-0.041179,0.046480,0.046566,-0.013474,-0.021587,0.138674,-0.031329,0.062693,0.035620,16.280001,0.003290
2025-10-31,0.061815,-0.000270,0.112265,-0.008869,0.018606,0.014279,-0.014504,0.213284,0.038902,-0.018242,0.023837,17.440001,0.003185
2025-11-30,0.032364,-0.048047,-0.045041,0.006300,0.102524,0.022507,-0.014697,-0.002598,0.061248,0.092212,0.001950,16.350000,0.003177
2025-12-31,-0.020692,-0.009207,-0.002959,0.033027,-0.000048,0.043737,-0.027740,0.002831,-0.034982,0.014824,0.008268,14.330000,0.003008

In [9]:
#Reconstruct back to csv 
adj_close.to_csv('C:\\Users\\jtjua\\arturo\\Wasserstein-Kelly\\data\\processed\\monthly_adj_close.csv')
monthly_panel.to_csv('C:\\Users\\jtjua\\arturo\\Wasserstein-Kelly\\data\\processed\\monthly_panel.csv')